### PR TITLE
fix: CreatePage tool fix -- split content if it exceeds length limit 2000

### PR DESCRIPTION
**Pull request by tybalex**
This PR aims to fix issue https://github.com/otto8-ai/otto8/issues/627.

*What is fixed*:
the `CreatePage` tool now will check the length of input content, and if it's greater than the limit(2000), the tool will slice the content into smaller chunks as multiple rich_texts of the the children block of the page.

Screenshot 2024-12-06 at 8 23 36 AM

### CODE REVIEW

**Comment by cjellick** [comment]
Does this end up looking like separate blocks? Like, if the post is one long paragraph that goes over 2k characters, will that paragraph get split into separate blocks?

**Comment by tybalex** [comment]
> Does this end up looking like separate blocks? Like, if the post is one long paragraph that goes over 2k characters, will that paragraph get split into separate blocks?

Yes, a long paragraph without `\n` will be spliced by `.`, in this case this paragraph gets split into separate blocks.

**Comment by tybalex** [comment]
Just made an update such that the function will create multiple `rich_text` instead of creating multiple blocks. So the user won't even tell the text got split.
@cjellick Tested this approach with a long paragraph and looks like it works well. The text does not get split into 2 paragraphs in notion page.
Screenshot 2024-12-06 at 10 33 47 AM

**Review by g-linville — APPROVED** [review]
If you're willing, can you remove the semicolons from the new code? It looks like the other code for this tool does not use semicolons. I wish JavaScript either explicitly required or forbade them, instead of making them optional, lol.

**Comment by cjellick** [comment]
@g-linville you should go ahead and request chanes rather than approve this. i think its wort being explicit and intentional about enforcing something like that

**Review by g-linville — CHANGES_REQUESTED** [review]
Requesting changes for semicolons to be removed

**Comment by tybalex** [comment]
> Requesting changes for semicolons to be removed

Removed all semicolons as requested.

**Review by g-linville — APPROVED** [review]

**Pull request merged**
